### ISSUE TITLE
need cubemx  configuration process 

### ISSUE THREAD

**Issue by U-Smiles** [vladajankovic/STM32F103R6-MCU-project#1]
your project is really nice work! can u share the process of cubemx configuration,thanks alot!

**Comment by vladajankovic** [comment]
Than you very much! Appreciate it :D

Based of the image of the project (and exam specifications that i barely remember), the CubeMX configuration is as follows:
 - FREERTOS interface -> CMSIS_V2 
   - Since this project is using FreeRTOS, nothing else configurated here i think
 - SYS timebase source -> TIM2 
   - FreeRTOS uses the MCUs SysTick, so the timebase must be changed to another source (in this case TIM2, since TIM1 and TIM3 will be used in the project)
 - USART1 mode -> Asynchronous 
   - default setup for UART (baud rate: 9600, word length: 9, parity: None, stop bits: 1)
   - USART1 global interrupt enabled in NVIC, because we want to communicte (send and receive messages) via interrupts
 - ADC1 mode -> IN7 
   - default setup for ADC1
 - TIM1 -> Channel1 - Input capture direct mode, Channel2 - Input capture direct mode
   - TIM1 uses the internal clock which is 8MH (I think) so the prescaler is set to 999 to divide 8 MHz with 1000. This means that in 1 second, the TIM1 will increase his counter by 8000. Counter Period 65535 which is the upper limit for the counter before it resets to 0, and counts upwards again. For the Input Capture Channel 1, Polarity Selection is set to Rising Edge so it triggers whenever the input signal changes from 0 to 1. This is used in the project to calculate the period and frequency of the signal from the Anemometer. The Input Cpature Channe 2 is set to detect Falling Edge but it is not used in the project, rather its an alternative way to calculate the signal period.
   - TIM1 capture compare interrupt enabled in NVIC, for triggering interrupts on rising edge
   - TIM1 update interrupt enabled in NVIC, for togling the LED and incrementing a variable to prevent value overflows when calculating the signal period
 - TIM3 -> Channel4 - PWM Generation CH4
   - Prescaler is set to 7999, so the timer runs at 1000 Hz, and the Counter preload is set to 9. For the PWM Generation Channel 4, mode is PWM mode 1, Pulse is 4 and CH polarity is Low. This is specific for the motor task as the CCR4 value changes based on the ARR (AutoReload Register). The CCR4 value states that if you count from 0 to CCR4 the output is 1 and from CCR4 to 9 the output is 0. I think the Pulse sets the CCR4s initial value, bit the value is changed in the project based on the temperature value.
 - Pins PC0-PC6 are all output pull down, for the LCD to send commands and data
 - Pin PA6 is output pull down, for Multiplexer input selection
 - Pin PA13 is output pull down, for toggling a LED 
 - Pin PA14 is set for the base GPIO external interrupt (with rising edge detection), as it detects the inpulse from the Raingauge when it is filled
   - EXTI line[15:10] interrupts enabled in NVIC 
  
I think that covers all for the CubeMX configuration process...
Hope my explanation helped :)

**Comment by U-Smiles** [comment]
appreciated for patient explanation! 
BTW u can just tell me open `project-master\code\code.ioc`
Anyway thank alot !💓👊
